### ISSUE TITLE
Řádkování v šabloně je defaultně nastaveno na 1

### ISSUE THREAD

**Issue by josse7cz** [xdobro4/uhk-thesis-latex-template#1]
Ahoj, všiml jsem si, že v šabloně má řádkování hodnotu jedna. Dle UHK šablony je to 1,5. Vyřešil jsem přidáním řádku do souboru main.tex na řádek 32.
\renewcommand{\baselinestretch}{1.5}

**Comment by spisovatelprogramu** [comment]
solved by merge https://github.com/spisovatelprogramu/uhk-thesis-latex-template/pull/2
